# Traefik is the single entry point of the cluster from the Internet.

service:
  # Azure gives this LoadBalancer Service a public IP.
  annotations:
    # Gives the IP the free name gitlab-runner-mpetit.francecentral.cloudapp.azure.com.
    service.beta.kubernetes.io/azure-dns-label-name: gitlab-runner-mpetit

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 256Mi
